#!/usr/bin/env node

/**
 * Module dependencies.
 */
const program = require("commander");
const { prompt } = require("inquirer");
const package = require("./package.json");
const Import = require("./src/importer");

const questions = [
  {
    type: "confirm",
    name: "confirmContinue",
    message:
      "Please ensure TablePlus and Sequel Ace are both closed. This script is intended for use on a fresh installation of TablePlus and will migrate any existing connections if it is running. Do you wish to continue?",
  },
];

program
  .version(package.version)
  .description(package.description)
  .action(() => {
    prompt(questions).then((answers) => {
      new Import(answers);
    });
  });

program.parse(process.argv);
